/**
 * Ekta — 14th floor, Neeldhara — GENERATED by CAD/tools/export_app.py.
 * Do not edit: change the design and re-run the export.
 */

import type { BuildingData } from '../../data/schema'

export const MIRROR_X = 0
export const POD_PARENTS = null
export const POD_KARAN = null

export const building: BuildingData = {
  meta: {
    project: 'Ekta — 14th floor, Neeldhara',
    drawing: 'BUILDER',
    revision: "imported from the builder's DWG · 1073 sq ft RERA",
    date: 'imported',
    scaleNote: 'Imported from the builder\u2019s DWG: wall centrelines paired from his drawn faces, doors off his door layer, envelope from the RERA carpet boundary. Every room checked against his own dimension text. Not yet designed.',
  },
  envelope: [{ x: -150, y: -150 }, { x: 3200, y: -150 }, { x: 3200, y: 470 }, { x: 8295, y: 470 }, { x: 8295, y: -150 }, { x: 11620, y: -150 }, { x: 11620, y: 8505 }, { x: 8295, y: 8505 }, { x: 8295, y: 7895 }, { x: 6950, y: 7895 }, { x: 6950, y: 12470 }, { x: 3650, y: 12470 }, { x: 3650, y: 11070 }, { x: 455, y: 11070 }, { x: 455, y: 9550 }, { x: 2145, y: 9550 }, { x: 2145, y: 4270 }, { x: -150, y: 4270 }],
  thickness: { exterior: 150, interior: 150, partition: 125 },
  levels: { ceiling: 3050, doorHead: 2100, windowSill: 750, windowHead: 2400 },
  exteriorOpenings: [],
  envelopeGlazing: [],
  walls: [
    { id: 'W-BED-E', points: [{ x: 3125, y: 545 }, { x: 3125, y: 4195 }], thickness: 125, kind: 'partition', notes: 'bedroom | common toilet and its passage. Solid from 770 to 1670: that gap in the drawn faces is a column, not an opening.', openings: [{ id: 'W-BED-E-O1', type: 'door', at: [2675, 3575], head: 2100, sill: 0 }] },
    { id: 'W-CT-S', points: [{ x: 3125, y: 3157.5 }, { x: 4607.5, y: 3157.5 }], thickness: 125, kind: 'partition', notes: 'common toilet | passage', openings: [{ id: 'W-CT-S-O1', type: 'door', at: [50, 800], head: 2100, sill: 0 }] },
    { id: 'W-KIT-W', points: [{ x: 4607.5, y: 545 }, { x: 4607.5, y: 4195 }], thickness: 125, kind: 'partition', notes: 'common toilet and passage | kitchen', openings: [] },
    { id: 'W-KIT-E', points: [{ x: 6875, y: 545 }, { x: 6875, y: 4195 }], thickness: 125, kind: 'partition', notes: 'kitchen | master toilet 01 and its passage', openings: [] },
    { id: 'W-T1-S', points: [{ x: 6875, y: 3157.5 }, { x: 8370, y: 3157.5 }], thickness: 125, kind: 'partition', notes: 'master toilet 01 | passage', openings: [{ id: 'W-T1-S-O1', type: 'door', at: [50, 800], head: 2100, sill: 0 }] },
    { id: 'W-B1-W', points: [{ x: 8370, y: 545 }, { x: 8370, y: 4195 }], thickness: 125, kind: 'partition', notes: 'master toilet 01 and its passage | m.bedroom 01. Solid above 1670: a column fills the wall there.', openings: [{ id: 'W-B1-W-O1', type: 'door', at: [2675, 3575], head: 2100, sill: 0 }] },
    { id: 'W-P1-S', points: [{ x: 2220, y: 4195 }, { x: 3625, y: 4195 }], thickness: 125, kind: 'partition', notes: 'bedroom and its passage | living/dining', openings: [] },
    { id: 'W-P2-S', points: [{ x: 6875, y: 4195 }, { x: 11545, y: 4195 }], thickness: 125, kind: 'partition', notes: 'passage and m.bedroom 01 | passage and m.bedroom 02', openings: [{ id: 'W-P2-S-O1', type: 'door', at: [50, 970], head: 2100, sill: 0 }] },
    { id: 'W-T2-N', points: [{ x: 6875, y: 5232.5 }, { x: 8370, y: 5232.5 }], thickness: 125, kind: 'partition', notes: 'passage | master toilet 02', openings: [] },
    { id: 'W-T2-W', points: [{ x: 6875, y: 5232.5 }, { x: 6875, y: 7820 }], thickness: 125, kind: 'partition', notes: 'living/dining | master toilet 02', openings: [] },
    { id: 'W-B2-W', points: [{ x: 8370, y: 4195 }, { x: 8370, y: 7820 }], thickness: 125, kind: 'partition', notes: 'passage and master toilet 02 | m.bedroom 02. The lower door is the ensuite: toilet 02 is entered from the bedroom, not the passage.', openings: [{ id: 'W-B2-W-O1', type: 'door', at: [50, 970], head: 2100, sill: 0 }, { id: 'W-B2-W-O2', type: 'door', at: [1100, 1845], head: 2100, sill: 0 }] },
    { id: 'T-P1-S', points: [{ x: 3625, y: 4195 }, { x: 4607.5, y: 4195 }], thickness: 0, kind: 'threshold', renderPane: false, notes: 'passage | living/dining — cased opening', openings: [] },
    { id: 'T-KIT-S', points: [{ x: 4607.5, y: 4195 }, { x: 6875, y: 4195 }], thickness: 0, kind: 'threshold', renderPane: false, notes: 'kitchen | living/dining — the kitchen is open', openings: [] },
    { id: 'T-P3-W', points: [{ x: 6875, y: 4195 }, { x: 6875, y: 5232.5 }], thickness: 0, kind: 'threshold', renderPane: false, notes: 'living/dining | passage — cased opening', openings: [] },
    { id: 'T-FOYER', points: [{ x: 2220, y: 9625 }, { x: 2220, y: 10995 }], thickness: 0, kind: 'threshold', renderPane: false, notes: 'foyer | living/dining — the foyer is an alcove', openings: [] },
    { id: 'T-BALC', points: [{ x: 3725, y: 10995 }, { x: 6875, y: 10995 }], thickness: 0, kind: 'threshold', renderPane: false, notes: 'living/dining | balcony — the sliding door', openings: [] },
  ],
  cores: [],
  cages: [],
  rooms: [
    { id: 'R-BEDROOM', name: 'Bedroom', anchor: { x: 1015, y: 1775 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', publishedSqFt: 135, notes: '10\'0"x13\'6"' },
    { id: 'R-TOILET-COMMON', name: 'Toilet', anchor: { x: 3503, y: 1789 }, category: 'wet', zone: 'flat', carpet: true, finish: 'Stone', publishedSqFt: 36, notes: '4\'6"x8\'1"' },
    { id: 'R-PASSAGE-BEDROOM', name: 'Passage', anchor: { x: 3408, y: 3619 }, category: 'circulation', zone: 'flat', carpet: true, finish: 'Stone', publishedSqFt: 13, notes: '4\'6"x2\'11"' },
    { id: 'R-KITCHEN', name: 'Kitchen', anchor: { x: 5325, y: 2346 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', publishedSqFt: 83, notes: '7\'0"x11\'11" · open to the living room' },
    { id: 'R-TOILET-01-MASTER', name: 'Toilet 01', anchor: { x: 7110, y: 1790 }, category: 'wet', zone: 'flat', carpet: true, finish: 'Stone', publishedSqFt: 36, notes: '4\'6"x8\'1"' },
    { id: 'R-PASSAGE-MASTER-01', name: 'Passage', anchor: { x: 7196, y: 3619 }, category: 'circulation', zone: 'flat', carpet: true, finish: 'Stone', publishedSqFt: 13, notes: '4\'6"x2\'11"' },
    { id: 'R-M-BEDROOM-01', name: 'M.Bedroom 01', anchor: { x: 9204, y: 1770 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', publishedSqFt: 135, notes: '10\'0"x13\'6"' },
    { id: 'R-LIVING-DINING', name: 'Living / Dining', anchor: { x: 3901, y: 6762 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', publishedSqFt: 323, notes: '14\'9"x21\'11" · the foyer is its entrance alcove and the kitchen opens off it' },
    { id: 'R-PASSAGE-MASTER-02', name: 'Passage', anchor: { x: 7117, y: 4619 }, category: 'circulation', zone: 'flat', carpet: true, finish: 'Stone', publishedSqFt: 14, notes: '4\'10"x3\'0"' },
    { id: 'R-TOILET-02-MASTER', name: 'Toilet 02', anchor: { x: 7079, y: 6513 }, category: 'wet', zone: 'flat', carpet: true, finish: 'Stone', publishedSqFt: 36, notes: '4\'6"x8\'0" · entered from the bedroom, not the passage' },
    { id: 'R-M-BEDROOM-02', name: 'M.Bedroom 02', anchor: { x: 9065, y: 6198 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', publishedSqFt: 135, notes: '10\'0"x13\'6"' },
    { id: 'R-FOYER', name: 'Foyer', anchor: { x: 1197, y: 10209 }, category: 'circulation', zone: 'flat', carpet: true, finish: 'Stone', publishedSqFt: 22, notes: '5\'7"x4\'0" · the way in' },
    { id: 'R-BALCONY', name: 'Balcony', anchor: { x: 4798, y: 11600 }, category: 'outdoor', zone: 'flat', carpet: false, finish: 'Stone', publishedSqFt: 41, notes: '10\'0"x4\'1" · off the living room' },
  ],
  stacks: [],
  glassRoofs: [],
  portals: [],
  screens: [],
}
