/**
 * Ekta — 14th floor, Neeldhara — GENERATED by CAD/tools/export_app.py.
 * Do not edit: change the design and re-run the export.
 */

import type { BuildingData } from '../../data/schema'

export const MIRROR_X = 0
export const POD_PARENTS = null
export const POD_KARAN = null

export const building: BuildingData = {
  meta: {
    project: 'Ekta — 14th floor, Neeldhara',
    drawing: 'BUILDER',
    revision: "imported from the builder's DWG · 1073 sq ft RERA",
    date: 'imported',
    scaleNote: 'Imported from the builder\u2019s DWG: wall centrelines paired from drawn faces, envelope from the RERA carpet boundary. Not yet designed.',
  },
  envelope: [{ x: 455, y: 1250 }, { x: 3650, y: 1250 }, { x: 3650, y: 1100 }, { x: 6950, y: 1100 }, { x: 6950, y: 4425 }, { x: 8295, y: 4425 }, { x: 8295, y: 3815 }, { x: 11620, y: 3815 }, { x: 11620, y: 12470 }, { x: 8295, y: 12470 }, { x: 8295, y: 11850 }, { x: 3200, y: 11850 }, { x: 3200, y: 12470 }, { x: -150, y: 12470 }, { x: -150, y: 8050 }, { x: 2145, y: 8050 }, { x: 2145, y: 2770 }, { x: 455, y: 2770 }],
  thickness: { exterior: 150, interior: 150, partition: 125 },
  levels: { ceiling: 3050, doorHead: 2100, windowSill: 750, windowHead: 2400 },
  exteriorOpenings: [],
  envelopeGlazing: [],
  walls: [
    { id: 'W-01', points: [{ x: 6875, y: 4500 }, { x: 6875, y: 11775 }], thickness: 125, kind: 'partition', openings: [] },
    { id: 'W-02', points: [{ x: 8370, y: 4500 }, { x: 8370, y: 7087 }], thickness: 125, kind: 'partition', openings: [] },
    { id: 'W-03', points: [{ x: 4607, y: 7087 }, { x: 4607, y: 11775 }], thickness: 125, kind: 'partition', openings: [] },
    { id: 'W-04', points: [{ x: 4607, y: 7087 }, { x: 8420, y: 7087 }], thickness: 125, kind: 'partition', openings: [] },
    { id: 'W-05', points: [{ x: 2220, y: 8125 }, { x: 4607, y: 8125 }], thickness: 125, kind: 'partition', openings: [] },
    { id: 'W-06', points: [{ x: 3125, y: 8125 }, { x: 3125, y: 11775 }], thickness: 125, kind: 'partition', openings: [] },
    { id: 'W-07', points: [{ x: 6875, y: 8125 }, { x: 11545, y: 8125 }], thickness: 125, kind: 'partition', openings: [] },
    { id: 'W-08', points: [{ x: 3125, y: 9162 }, { x: 4607, y: 9162 }], thickness: 125, kind: 'partition', openings: [] },
    { id: 'W-09', points: [{ x: 6875, y: 9162 }, { x: 8370, y: 9162 }], thickness: 125, kind: 'partition', openings: [] },
    { id: 'W-10', points: [{ x: 8370, y: 9162 }, { x: 8370, y: 11775 }], thickness: 125, kind: 'partition', openings: [] },
  ],
  cores: [],
  cages: [],
  rooms: [
    { id: 'R-LIVING-DINING', name: 'Living / Dining', anchor: { x: 3901, y: 5558 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', notes: 'the long room, with the foyer as its entrance alcove — 14\'9" x 21\'11" as the builder set it out' },
    { id: 'R-KITCHEN', name: 'Kitchen', anchor: { x: 5325, y: 9974 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', notes: '7\' x 11\'11" plus the utility return' },
    { id: 'R-BEDROOM', name: 'Bedroom', anchor: { x: 1015, y: 10545 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', notes: '10\'0" x 13\'6"' },
    { id: 'R-M-BEDROOM-01', name: 'M.Bedroom 01', anchor: { x: 9204, y: 10550 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', notes: '10\'0" x 13\'6", with its own toilet' },
    { id: 'R-M-BEDROOM-02', name: 'M.Bedroom 02', anchor: { x: 9065, y: 6122 }, category: 'habitable', zone: 'flat', carpet: true, finish: 'Oak plank', notes: '10\'0" x 13\'6", with its own toilet' },
    { id: 'R-TOILET-01-MASTER', name: 'Toilet 01', anchor: { x: 7110, y: 10530 }, category: 'wet', zone: 'flat', carpet: true, finish: 'Stone', notes: '4\'6" x 8\'1"' },
    { id: 'R-TOILET-02-MASTER', name: 'Toilet 02', anchor: { x: 7079, y: 5807 }, category: 'wet', zone: 'flat', carpet: true, finish: 'Stone', notes: '4\'6" x 8\'0"' },
    { id: 'R-TOILET-COMMON', name: 'Toilet', anchor: { x: 3503, y: 10531 }, category: 'wet', zone: 'flat', carpet: true, finish: 'Stone', notes: '4\'6" x 8\'1"' },
    { id: 'R-PASSAGE', name: 'Passage', anchor: { x: 3408, y: 8701 }, category: 'circulation', zone: 'flat', carpet: true, finish: 'Stone', notes: '4\'6" x 2\'11", between the bedroom and the common toilet' },
  ],
  stacks: [],
  glassRoofs: [],
  portals: [],
  screens: [],
}
