#!/usr/bin/env python3
"""
GENERIC APP EXPORT — a home's design.py to the portal's data files.

docs/design-export.py in the web app is Om Neeldhara's: it knows that plan's
mirror line, its curved pod screens and its bespoke joinery, and it must keep
producing byte-identical output. This is the plain path, for a home whose
design.py provides only the generic contract:

    ENVELOPE · NEW_WALLS · GLAZING · ROOMS · FURNITURE

Rooms carry an anchor and no shape — the app derives every room polygon from
the wall centrelines, so that is genuinely all it needs.

    python3 export_app.py --home <id> --out <webapp>/src/homes/<id>
"""

import argparse
import os
import shutil
import sys

import home


def fnum(v):
    s = f'{float(v):.3f}'.rstrip('0').rstrip('.')
    return s if s else '0'


def pt(x, y):
    return f'{{ x: {fnum(x)}, y: {fnum(y)} }}'


def slug(s, used):
    b = ''.join(c if c.isalnum() else '-' for c in s.upper()).strip('-')
    while '--' in b:
        b = b.replace('--', '-')
    n, out = 1, f'R-{b}'
    while out in used:
        n += 1
        out = f'R-{b}-{n}'
    used.add(out)
    return out


CATEGORY = {'TOILET': 'wet', 'BATH': 'wet', 'PASSAGE': 'circulation',
            'FOYER': 'circulation', 'BALCONY': 'outdoor', 'STORE': 'storage'}
FINISH = {'wet': 'Stone', 'outdoor': 'Stone', 'circulation': 'Stone'}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--home', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    home.select(a.home)
    import design as D

    meta = home.meta()
    os.makedirs(a.out, exist_ok=True)
    o = []
    A = o.append
    A('/**')
    A(f" * {meta['name']} — GENERATED by CAD/tools/export_app.py.")
    A(' * Do not edit: change the design and re-run the export.')
    A(' */')
    A('')
    A("import type { BuildingData } from '../../data/schema'")
    A('')
    A('export const MIRROR_X = 0')
    A('export const POD_PARENTS = null')
    A('export const POD_KARAN = null')
    A('')
    A('export const building: BuildingData = {')
    A('  meta: {')
    A(f"    project: {meta['name']!r},")
    A("    drawing: 'BUILDER',")
    A(f"    revision: {meta.get('subtitle', 'imported')!r},")
    A("    date: 'imported',")
    A("    scaleNote: 'Imported from the builder\\u2019s DWG: wall centrelines paired "
      "from drawn faces, envelope from the RERA carpet boundary. Not yet designed.',")
    A('  },')
    A('  envelope: [' + ', '.join(pt(x, y) for x, y in D.ENVELOPE) + '],')
    A('  thickness: { exterior: 150, interior: 150, partition: 125 },')
    A('  levels: { ceiling: 3050, doorHead: 2100, windowSill: 750, windowHead: 2400 },')
    A('  exteriorOpenings: [],')
    A('  envelopeGlazing: [],')
    A('  walls: [')
    for i, w in enumerate(D.NEW_WALLS, 1):
        x1, y1, x2, y2, t = w[:5]
        kind = w[6] if len(w) > 6 else 'partition'
        A(f"    {{ id: 'W-{i:02d}', points: [{pt(x1, y1)}, {pt(x2, y2)}], "
          f"thickness: {fnum(t)}, kind: {kind!r}, openings: [] }},")
    A('  ],')
    A('  cores: [],')
    A('  cages: [],')
    A('  rooms: [')
    used = set()
    for name, sub, (ax, ay), note in D.ROOMS:
        cat = 'habitable'
        for k, v in CATEGORY.items():
            if k in name.upper():
                cat = v
        rid = slug(name if not sub else f'{name}-{sub}', used)
        fin = FINISH.get(cat, 'Oak plank')
        A(f"    {{ id: {rid!r}, name: {name.title()!r}, anchor: {pt(ax, ay)}, "
          f"category: {cat!r}, zone: 'flat', carpet: {str(cat != 'outdoor').lower()}, "
          f"finish: {fin!r}, notes: {note!r} }},")
    A('  ],')
    A('  stacks: [],')
    A('  glassRoofs: [],')
    A('  portals: [],')
    A('  screens: [],')
    A('}')
    A('')
    open(os.path.join(a.out, 'building.ts'), 'w').write('\n'.join(o))

    open(os.path.join(a.out, 'fixtures.ts'), 'w').write(
        f"/**\n * {meta['name']} — GENERATED. No fixtures yet: this flat is "
        "imported,\n * not designed.\n */\n\n"
        "import type { FixtureDef } from '../../data/schema'\n\n"
        'export const fixtures: FixtureDef[] = []\n')

    open(os.path.join(a.out, 'furniture.ts'), 'w').write(
        f"/**\n * {meta['name']} — GENERATED. No furniture yet.\n */\n\n"
        "export type FurnitureKind =\n"
        "  | 'sofa' | 'bed' | 'daybed' | 'armchair' | 'table' | 'console'\n"
        "  | 'bench' | 'stool' | 'lounger' | 'rug' | 'plant' | 'tree'\n"
        "  | 'shelves' | 'dining' | 'chair' | 'drumkit' | 'guitar' | 'stair'\n"
        "  | 'wardrobe' | 'planter' | 'grass' | 'screen' | 'tv'\n\n"
        'export interface FurnitureItem {\n'
        '  id: string\n  kind: FurnitureKind\n  x: number\n  y: number\n'
        '  w: number\n  d: number\n'
        "  face?: 'N' | 'S' | 'E' | 'W'\n  room: string\n  label: string\n"
        '  height: number\n  seats?: [number, number]\n'
        '  poly?: { x: number; y: number }[]\n}\n\n'
        'export const furniture: FurnitureItem[] = []\n')

    sheet = os.path.join(home.CAD, meta['sheet'])
    if os.path.isfile(sheet):
        shutil.copyfile(sheet, os.path.join(a.out, 'plan-sheet.svg'))
        print('copied', meta['sheet'])
    print(f"wrote building.ts ({len(D.NEW_WALLS)} walls, {len(D.ROOMS)} rooms), "
          f'fixtures.ts, furniture.ts -> {a.out}')


if __name__ == '__main__':
    main()
