#!/usr/bin/env python3
"""
GENERIC APP EXPORT — a home's design.py to the portal's data files.

docs/design-export.py in the web app is Om Neeldhara's: it knows that plan's
mirror line, its curved pod screens and its bespoke joinery, and it must keep
producing byte-identical output. This is the plain path, for a home whose
design.py provides only the generic contract:

    ENVELOPE · NEW_WALLS · GLAZING · ROOMS · FURNITURE

    NEW_WALLS  (x1, y1, x2, y2, thickness, openings, kind[, id, note, bow])
               openings are (type, from, to[, sill, head]) ABSOLUTE along the
               wall's own axis; a wall
               of thickness 0 and kind 'threshold' divides two rooms without
               putting anything on the floor; `bow` is the sagitta in mm and
               becomes a quadratic Bezier, positive to the LEFT of travel.
    SCREENS    (x1, y1, x2, y2, bow, height, id, name, note) — optional. NOT
               walls: they stop below the ceiling and divide no rooms.
    EXTERIOR_OPENINGS
               (x1, y1, x2, y2, type, id, note) — optional, endpoints on the
               OUTER face of the envelope.
    ROOMS      (name, subtitle, anchor, note[, dimension text, sq ft])

Rooms carry an anchor and no shape — the app derives every room polygon from
the wall centrelines, so that is genuinely all it needs. Where a home gives
the last two columns, they are the SOURCE drawing's own dimension text and
its area: the app carries them as `publishedSqFt` so the derivation can be
checked against the drawing it came from.

    python3 export_app.py --home <id> --out <webapp>/src/homes/<id>
"""

import argparse
import os
import shutil
import sys

import home


def fnum(v):
    s = f'{float(v):.3f}'.rstrip('0').rstrip('.')
    return s if s else '0'


def pt(x, y):
    return f'{{ x: {fnum(x)}, y: {fnum(y)} }}'


def flatten(x1, y1, x2, y2, bow, n=256):
    """The wall as points. Straight walls are two."""
    if not bow:
        return [(x1, y1), (x2, y2)]
    cx, cy = control(x1, y1, x2, y2, bow)
    out = []
    for i in range(n + 1):
        t = i / n
        u = 1 - t
        out.append((u * u * x1 + 2 * u * t * cx + t * t * x2,
                    u * u * y1 + 2 * u * t * cy + t * t * y2))
    return out


def arc_at(pts, vert, v):
    """Distance ALONG a wall to the point at axis position `v`.

    Openings are authored against the axis — the straight line between the
    wall's ends — because that is how they are measured on a drawing. The app
    places them by distance along the RUN. On a straight wall those are the
    same number; on a bowed one they are not, and a 1730 mm bow over 5245 mm
    makes the arc a fifth longer than its chord. Getting this wrong slides
    every window along the curve.
    """
    k = 1 if vert else 0
    run = 0.0
    for i in range(1, len(pts)):
        a, b = pts[i - 1], pts[i]
        seg = ((b[0] - a[0]) ** 2 + (b[1] - a[1]) ** 2) ** 0.5
        lo, hi = sorted((a[k], b[k]))
        if lo <= v <= hi and hi > lo:
            return run + seg * (v - a[k]) / (b[k] - a[k])
        run += seg
    return run


def control(x1, y1, x2, y2, bow):
    """The Bezier control point for a wall bowed by `bow`. A quadratic sits
    half way to its control point at t=0.5, so the control is offset by TWICE
    the sagitta — which is what makes `bow` mean the distance you can measure
    on the drawing."""
    dx, dy = x2 - x1, y2 - y1
    L = (dx * dx + dy * dy) ** 0.5 or 1.0
    nx, ny = -dy / L, dx / L
    return ((x1 + x2) / 2 + nx * 2 * bow, (y1 + y2) / 2 + ny * 2 * bow)


def slug(s, used):
    b = ''.join(c if c.isalnum() else '-' for c in s.upper()).strip('-')
    while '--' in b:
        b = b.replace('--', '-')
    n, out = 1, f'R-{b}'
    while out in used:
        n += 1
        out = f'R-{b}-{n}'
    used.add(out)
    return out


CATEGORY = {'TOILET': 'wet', 'BATH': 'wet', 'PASSAGE': 'circulation',
            'FOYER': 'circulation', 'BALCONY': 'outdoor', 'STORE': 'storage'}
FINISH = {'wet': 'Stone', 'outdoor': 'Stone', 'circulation': 'Stone'}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--home', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    home.select(a.home)
    import design as D

    meta = home.meta()
    os.makedirs(a.out, exist_ok=True)
    o = []
    A = o.append
    A('/**')
    A(f" * {meta['name']} — GENERATED by CAD/tools/export_app.py.")
    A(' * Do not edit: change the design and re-run the export.')
    A(' */')
    A('')
    A("import type { BuildingData } from '../../data/schema'")
    A('')
    A('export const MIRROR_X = 0')
    A('export const POD_PARENTS = null')
    A('export const POD_KARAN = null')
    A('')
    A('export const building: BuildingData = {')
    A('  meta: {')
    A(f"    project: {meta['name']!r},")
    A("    drawing: 'BUILDER',")
    A(f"    revision: {meta.get('subtitle', 'imported')!r},")
    A("    date: 'imported',")
    A("    scaleNote: 'Imported from the builder\\u2019s DWG: wall centrelines paired "
      "from his drawn faces, doors off his door layer, envelope from the RERA "
      "carpet boundary. Every room checked against his own dimension text. "
      "Not yet designed.',")
    A('  },')
    A('  envelope: [' + ', '.join(pt(x, y) for x, y in D.ENVELOPE) + '],')
    A('  thickness: { exterior: 150, interior: 150, partition: 125 },')
    A('  levels: { ceiling: 3050, doorHead: 2100, windowSill: 750, windowHead: 2400 },')
    A('  exteriorOpenings: [')
    for eo in getattr(D, 'EXTERIOR_OPENINGS', []):
        x1, y1, x2, y2, typ, oid = eo[:6]
        note = eo[6] if len(eo) > 6 else None
        head = 2100 if typ in ('door', 'cased', 'arch') else 2400
        sill = 0 if typ in ('door', 'cased', 'arch') else 750
        A(f"    {{ id: {oid!r}, type: {typ!r}, abs: [{pt(x1, y1)}, {pt(x2, y2)}], "
          f'head: {head}, sill: {sill}'
          + (f', notes: {note!r}' if note else '') + ' },')
    A('  ],')
    A('  envelopeGlazing: [],')
    A('  walls: [')
    for i, w in enumerate(D.NEW_WALLS, 1):
        x1, y1, x2, y2, t = w[:5]
        ops = w[5] if len(w) > 5 else []
        kind = w[6] if len(w) > 6 else 'partition'
        wid = w[7] if len(w) > 7 else f'W-{i:02d}'
        note = w[8] if len(w) > 8 else None
        bow = w[9] if len(w) > 9 else 0
        # An opening is authored in absolute mm along the wall, because that is
        # how it is read off the drawing. The app wants it as a distance from
        # the run's first point.
        vert = abs(x2 - x1) < abs(y2 - y1)
        base = y1 if vert else x1
        sgn = 1 if (y2 > y1 if vert else x2 > x1) else -1
        pts = flatten(x1, y1, x2, y2, bow)
        oo = []
        for j, op in enumerate(ops, 1):
            typ, f0, f1 = op[:3]
            sill = op[3] if len(op) > 3 else 0
            head = op[4] if len(op) > 4 else (2400 if typ == 'window' else 2100)
            if bow:
                a0, a1 = arc_at(pts, vert, f0), arc_at(pts, vert, f1)
            else:
                a0, a1 = sgn * (f0 - base), sgn * (f1 - base)
            d0, d1 = sorted((a0, a1))
            oo.append(f"{{ id: '{wid}-O{j}', type: {typ!r}, "
                      f'at: [{fnum(d0)}, {fnum(d1)}], head: {fnum(head)}, '
                      f'sill: {fnum(sill)} }}')
        if bow:
            cx, cy = control(x1, y1, x2, y2, bow)
            shape = (f'curve: {{ p0: {pt(x1, y1)}, p1: {pt(cx, cy)}, '
                     f'p2: {pt(x2, y2)} }}')
        else:
            shape = f'points: [{pt(x1, y1)}, {pt(x2, y2)}]'
        A(f"    {{ id: {wid!r}, {shape}, "
          f"thickness: {fnum(t)}, kind: {kind!r},"
          + (f' renderPane: false,' if t == 0 else '')
          + (f" notes: {note!r}," if note else '')
          + ' openings: [' + ', '.join(oo) + '] },')
    A('  ],')
    A('  cores: [],')
    A('  cages: [],')
    A('  rooms: [')
    used = set()
    for r in D.ROOMS:
        name, sub, (ax, ay), note = r[:4]
        text, sq = (r[4], r[5]) if len(r) > 5 else (None, None)
        cat = 'habitable'
        for k, v in CATEGORY.items():
            if k in name.upper():
                cat = v
        rid = slug(name if not sub else f'{name}-{sub}', used)
        fin = FINISH.get(cat, 'Oak plank')
        full = ' · '.join(x for x in (text, note) if x)
        A(f"    {{ id: {rid!r}, name: {name.title()!r}, anchor: {pt(ax, ay)}, "
          f"category: {cat!r}, zone: 'flat', carpet: {str(cat != 'outdoor').lower()}, "
          f"finish: {fin!r},"
          + (f' publishedSqFt: {sq},' if sq else '')
          + f' notes: {full!r} }},')
    A('  ],')
    A('  stacks: [],')
    A('  glassRoofs: [],')
    A('  portals: [],')
    A('  screens: [')
    for sc in getattr(D, 'SCREENS', []):
        x1, y1, x2, y2, bow, h, sid, name = sc[:8]
        note = sc[8] if len(sc) > 8 else ''
        cx, cy = control(x1, y1, x2, y2, bow)
        A(f"    {{ id: {sid!r}, name: {name!r}, curve: {{ p0: {pt(x1, y1)}, "
          f'p1: {pt(cx, cy)}, p2: {pt(x2, y2)} }}, height: {fnum(h)}, '
          f'notes: {note!r} }},')
    A('  ],')
    A('}')
    A('')
    open(os.path.join(a.out, 'building.ts'), 'w').write('\n'.join(o))

    open(os.path.join(a.out, 'fixtures.ts'), 'w').write(
        f"/**\n * {meta['name']} — GENERATED. No fixtures yet: this flat is "
        "imported,\n * not designed.\n */\n\n"
        "import type { FixtureDef } from '../../data/schema'\n\n"
        'export const fixtures: FixtureDef[] = []\n')

    fitems = []
    for i, f in enumerate(getattr(D, 'FURNITURE', []), 1):
        kind, x1, y1, x2, y2, label = f[:6]
        room = f[6] if len(f) > 6 else ''
        height = f[7] if len(f) > 7 else 750
        poly = f[8] if len(f) > 8 else None
        shape = ('' if not poly else
                 ', poly: [' + ', '.join(pt(px, py) for px, py in poly) + ']')
        fitems.append(
            f"  {{ id: 'F-{i:02d}', kind: {kind!r}, x: {fnum(min(x1, x2))}, "
            f'y: {fnum(min(y1, y2))}, w: {fnum(abs(x2 - x1))}, '
            f'd: {fnum(abs(y2 - y1))}, room: {room!r}, label: {label!r}, '
            f'height: {fnum(height)}{shape} }},')

    open(os.path.join(a.out, 'furniture.ts'), 'w').write(
        f"/**\n * {meta['name']} — GENERATED by CAD/tools/export_app.py.\n */\n\n"
        "export type FurnitureKind =\n"
        "  | 'sofa' | 'bed' | 'daybed' | 'armchair' | 'table' | 'console'\n"
        "  | 'bench' | 'stool' | 'lounger' | 'rug' | 'plant' | 'tree'\n"
        "  | 'shelves' | 'dining' | 'chair' | 'drumkit' | 'guitar' | 'stair'\n"
        "  | 'wardrobe' | 'planter' | 'grass' | 'screen' | 'tv'\n\n"
        'export interface FurnitureItem {\n'
        '  id: string\n  kind: FurnitureKind\n  x: number\n  y: number\n'
        '  w: number\n  d: number\n'
        "  face?: 'N' | 'S' | 'E' | 'W'\n  room: string\n  label: string\n"
        '  height: number\n  seats?: [number, number]\n'
        '  poly?: { x: number; y: number }[]\n}\n\n'
        'export const furniture: FurnitureItem[] = [\n'
        + '\n'.join(fitems) + ('\n' if fitems else '') + ']\n')

    sheet = os.path.join(home.CAD, meta['sheet'])
    if os.path.isfile(sheet):
        shutil.copyfile(sheet, os.path.join(a.out, 'plan-sheet.svg'))
        print('copied', meta['sheet'])
    print(f"wrote building.ts ({len(D.NEW_WALLS)} walls, {len(D.ROOMS)} rooms), "
          f'fixtures.ts, furniture.ts -> {a.out}')


if __name__ == '__main__':
    main()
