/**
 * Sanitaryware and fitted appliances — GENERATED by docs/design-export.py.
 * Fabric, not furniture: these tie each wet room to its stack.
 */

import type { FixtureDef } from './schema'

export const fixtures: FixtureDef[] = [
  { id: 'FX-SINK-0', kind: 'sink', at: { x: 8360, y: 8825 }, size: [600, 450], room: 'R-KITCHEN', stack: 'STK-KITCHEN', label: 'Sink' },
  { id: 'FX-DW-1', kind: 'washer', at: { x: 8800, y: 10675 }, size: [600, 570], room: 'R-KITCHEN', stack: 'STK-KITCHEN', label: 'Integrated dishwasher' },
  { id: 'FX-HOB-2', kind: 'hob', at: { x: 8800, y: 10675 }, size: [600, 510], room: 'R-KITCHEN', label: 'Hob, 600 × 510' },
  { id: 'FX-FR-3', kind: 'fridge', at: { x: 7400, y: 10625 }, size: [800, 700], room: 'R-KITCHEN', label: 'Tall fridge' },
  { id: 'FX-FR-4', kind: 'fridge', at: { x: 6055, y: 10700 }, size: [600, 650], room: 'R-KITCHEN', label: 'Tall fridge' },
  { id: 'FX-SH-5', kind: 'shower', at: { x: 16980, y: 8875 }, size: [900, 900], room: 'R-GUEST-BATH', stack: 'STK-GUEST', label: 'Shower' },
  { id: 'FX-WC-6', kind: 'wc', at: { x: 17090, y: 9625 }, size: [680, 390], room: 'R-GUEST-BATH', stack: 'STK-GUEST', label: 'WC' },
  { id: 'FX-WC-7', kind: 'wc', at: { x: 4065, y: 7820 }, size: [680, 390], room: 'R-P-BATH', stack: 'STK-P-BATH', label: 'WC' },
  { id: 'FX-SH-8', kind: 'shower', at: { x: 3400, y: 9070 }, size: [1850, 950], room: 'R-P-BATH', stack: 'STK-P-BATH', label: 'Shower' },
  { id: 'FX-WC-9', kind: 'wc', at: { x: 20415, y: 7820 }, size: [680, 390], room: 'R-K-BATH', stack: 'STK-K-BATH', label: 'WC' },
  { id: 'FX-SH-10', kind: 'shower', at: { x: 21080, y: 9070 }, size: [1850, 950], room: 'R-K-BATH', stack: 'STK-K-BATH', label: 'Shower' },
  { id: 'FX-CTR-1', kind: 'counter', at: { x: 8973.008, y: 8525 }, size: [4146.015, 1200], room: 'R-KITCHEN', label: 'Counter run' },
  { id: 'FX-CTR-2', kind: 'counter', at: { x: 9100, y: 10337.5 }, size: [2600, 1275], room: 'R-KITCHEN', label: 'Counter run' },
  { id: 'FX-P-VAN', kind: 'basin', at: { x: 3647.093, y: 6495.902 }, size: [1515.815, 941.802], room: 'R-P-BATH', stack: 'STK-P-BATH', label: 'Curved vanity, 400 bowl' },
  { id: 'FX-K-VAN', kind: 'basin', at: { x: 20832.907, y: 6495.902 }, size: [1515.815, 941.802], room: 'R-K-BATH', stack: 'STK-K-BATH', label: 'Curved vanity, 400 bowl' },
  { id: 'FX-G-VAN', kind: 'basin', at: { x: 15333.641, y: 8976.438 }, size: [557.282, 902.875], room: 'R-GUEST-BATH', stack: 'STK-GUEST', label: 'Curved console, 344 bowl' },
]
