/**
 * Loose furniture — GENERATED by docs/design-export.py from the CAD
 * design’s furniture schedule. Its own layer, excluded from integrity.
 */

export type FurnitureKind =
  | 'sofa' | 'bed' | 'daybed' | 'armchair' | 'table' | 'console'
  | 'bench' | 'stool' | 'lounger' | 'rug' | 'plant' | 'tree'
  | 'shelves' | 'dining' | 'drumkit' | 'guitar' | 'stair' | 'wardrobe'

export interface FurnitureItem {
  id: string
  kind: FurnitureKind
  x: number
  y: number
  w: number
  d: number
  face?: 'N' | 'S' | 'E' | 'W'
  room: string
  label: string
  height: number
  seats?: [number, number]
}

export const furniture: FurnitureItem[] = [
  { id: 'FN-CONSOLE-1', kind: 'console', x: 3005, y: 1350, w: 1400, d: 600, room: 'R-DECK', label: 'study desk', height: 800 },
  { id: 'FN-CONSOLE-2', kind: 'console', x: 3805, y: 1950, w: 600, d: 670, room: 'R-DECK', label: 'study desk, return', height: 800 },
  { id: 'FN-ARMCHAIR-1', kind: 'armchair', x: 3155, y: 2030, w: 550, d: 550, room: 'R-DECK', label: 'desk chair', height: 780 },
  { id: 'FN-WARDROBE-1', kind: 'wardrobe', x: -450, y: 1950, w: 200, d: 3925, room: 'R-P-SUITE', label: 'headboard', height: 2300 },
  { id: 'FN-BED-1', kind: 'bed', x: -250, y: 2647, w: 2032, d: 1930, room: 'R-P-SUITE', label: 'king 1930 x 2032', height: 550 },
  { id: 'FN-CONSOLE-3', kind: 'console', x: -250, y: 2047, w: 450, d: 550, room: 'R-DECK', label: 'side table', height: 800 },
  { id: 'FN-CONSOLE-4', kind: 'console', x: -250, y: 4627, w: 450, d: 550, room: 'R-P-SUITE', label: 'side table', height: 800 },
  { id: 'FN-WARDROBE-2', kind: 'wardrobe', x: -450, y: 5875, w: 1850, d: 120, room: 'R-P-DRESSING', label: 'sliding pocket', height: 2300 },
  { id: 'FN-WARDROBE-3', kind: 'wardrobe', x: -450, y: 5995, w: 1850, d: 600, room: 'R-P-DRESSING', label: 'cupboards', height: 2300 },
  { id: 'FN-CONSOLE-5', kind: 'console', x: 1400, y: 5875, w: 1332, d: 120, room: 'R-P-DRESSING', label: 'sliding screen', height: 800 },
  { id: 'FN-CONSOLE-6', kind: 'console', x: -450, y: 6945, w: 480, d: 500, room: 'R-P-DRESSING', label: 'side table', height: 800 },
  { id: 'FN-BED-2', kind: 'bed', x: -370, y: 7445, w: 400, d: 1500, room: 'R-P-DRESSING', label: 'wall bed', height: 550, face: 'E' },
  { id: 'FN-CONSOLE-7', kind: 'console', x: -450, y: 8945, w: 480, d: 500, room: 'R-P-DRESSING', label: 'side table', height: 800 },
  { id: 'FN-CONSOLE-8', kind: 'console', x: 2310, y: 8605, w: 90, d: 940, room: 'R-P-DRESSING', label: 'mirror', height: 800 },
  { id: 'FN-SOFA-1', kind: 'sofa', x: 1750, y: 200, w: 800, d: 800, room: 'R-P-TERRACE', label: 'single sofa', height: 780, face: 'E' },
  { id: 'FN-SOFA-2', kind: 'sofa', x: 22280, y: 1400, w: 2000, d: 800, room: 'R-DECK', label: 'bench sofa', height: 780 },
  { id: 'FN-SOFA-3', kind: 'sofa', x: 21930, y: 200, w: 800, d: 800, room: 'R-K-TERRACE', label: 'single sofa', height: 780, face: 'W' },
  { id: 'FN-PLANT-1', kind: 'plant', x: 20180, y: 1350, w: 1200, d: 1200, room: 'R-DECK', label: 'large plant', height: 1200 },
  { id: 'FN-CONSOLE-9', kind: 'console', x: 20330, y: 1500, w: 900, d: 900, room: 'R-DECK', label: 'low wooden table', height: 800 },
  { id: 'FN-WARDROBE-4', kind: 'wardrobe', x: 24730, y: 1950, w: 200, d: 3635, room: 'R-K-SUITE', label: 'headboard', height: 2300 },
  { id: 'FN-BED-3', kind: 'bed', x: 22698, y: 3547.5, w: 2032, d: 1930, room: 'R-K-SUITE', label: 'king 1930 x 2032', height: 550 },
  { id: 'FN-CONSOLE-10', kind: 'console', x: 24280, y: 2947.5, w: 450, d: 550, room: 'R-K-SUITE', label: 'side table', height: 800 },
  { id: 'FN-CONSOLE-11', kind: 'console', x: 24280, y: 5527.5, w: 450, d: 550, room: 'R-K-SUITE', label: 'side table', height: 800 },
  { id: 'FN-WARDROBE-5', kind: 'wardrobe', x: 22155, y: 8865, w: 990, d: 600, room: 'R-K-DRESSING', label: 'wardrobe 1', height: 2300 },
  { id: 'FN-WARDROBE-6', kind: 'wardrobe', x: 23145, y: 8865, w: 990, d: 600, room: 'R-K-DRESSING', label: 'wardrobe 2', height: 2300 },
  { id: 'FN-CONSOLE-12', kind: 'console', x: 24135, y: 9015, w: 795, d: 450, room: 'R-K-DRESSING', label: 'dresser', height: 800, face: 'S' },
  { id: 'FN-SHELVES-1', kind: 'shelves', x: 4760, y: 340, w: 1200, d: 2000, room: 'R-DECK', label: 'All-in-one strength trainer', height: 2150 },
  { id: 'FN-TABLE-1', kind: 'table', x: 17930, y: 400, w: 1750, d: 1750, room: 'R-DECK', label: '4-seat spa', height: 880 },
  { id: 'FN-PLANT-2', kind: 'plant', x: 11640, y: 560, w: 1200, d: 1200, room: 'R-DECK', label: 'Marble fountain', height: 420 },
  { id: 'FN-LOUNGER-1', kind: 'lounger', x: 4900, y: 3120, w: 800, d: 900, room: 'R-P-FAMILY', label: 'recliner', height: 800, face: 'W' },
  { id: 'FN-SOFA-4', kind: 'sofa', x: 6300, y: 3770, w: 1700, d: 800, room: 'R-P-FAMILY', label: 'sofa', height: 780, face: 'S' },
  { id: 'FN-DINING-1', kind: 'dining', x: 6603, y: 5700, w: 1100, d: 2200, room: 'R-P-FAMILY', label: 'superellipse 1100 x 2200', height: 750, seats: [2, 1] },
  { id: 'FN-LOUNGER-2', kind: 'lounger', x: 9115, y: 945, w: 900, d: 1600, room: 'R-DECK', label: '2-seat recliner', height: 800, face: 'W' },
  { id: 'FN-TABLE-2', kind: 'table', x: 9115, y: 495, w: 450, d: 450, room: 'R-DECK', label: 'side table', height: 480 },
  { id: 'FN-LOUNGER-3', kind: 'lounger', x: 14465, y: 945, w: 900, d: 1600, room: 'R-DECK', label: '2-seat recliner', height: 800, face: 'E' },
  { id: 'FN-TABLE-3', kind: 'table', x: 14915, y: 495, w: 450, d: 450, room: 'R-DECK', label: 'side table', height: 480 },
  { id: 'FN-TABLE-4', kind: 'table', x: 9800, y: 3050, w: 450, d: 450, room: 'R-GREAT', label: 'side table', height: 480 },
  { id: 'FN-TABLE-5', kind: 'table', x: 13900, y: 3450, w: 450, d: 450, room: 'R-GREAT', label: 'side table', height: 480 },
  { id: 'FN-TABLE-6', kind: 'table', x: 12760, y: 4950, w: 400, d: 400, room: 'R-GREAT', label: 'side table', height: 480 },
  { id: 'FN-LOUNGER-4', kind: 'lounger', x: 9673, y: 3532, w: 900, d: 800, room: 'R-GREAT', label: 'recliner', height: 800, face: 'W' },
  { id: 'FN-CONSOLE-13', kind: 'console', x: 10878, y: 5537, w: 1600, d: 350, room: 'R-GREAT', label: 'console', height: 800, face: 'E' },
  { id: 'FN-CONSOLE-14', kind: 'console', x: 15880, y: 4800, w: 700, d: 2200, room: 'R-K-DEN', label: 'work console', height: 800 },
  { id: 'FN-WARDROBE-7', kind: 'wardrobe', x: 15920, y: 5150, w: 300, d: 680, room: 'R-K-DEN', label: 'monitor', height: 2300, face: 'W' },
  { id: 'FN-ARMCHAIR-2', kind: 'armchair', x: 16620, y: 5190, w: 600, d: 600, room: 'R-K-DEN', label: 'desk chair', height: 780 },
  { id: 'FN-LOUNGER-5', kind: 'lounger', x: 17380, y: 3670, w: 800, d: 900, room: 'R-K-DEN', label: 'recliner', height: 800, face: 'S' },
  { id: 'FN-TABLE-7', kind: 'table', x: 18180, y: 3970, w: 450, d: 600, room: 'R-K-DEN', label: 'side table', height: 480 },
  { id: 'FN-LOUNGER-6', kind: 'lounger', x: 18630, y: 3670, w: 800, d: 900, room: 'R-K-DEN', label: 'recliner', height: 800, face: 'S' },
  { id: 'FN-SHELVES-2', kind: 'shelves', x: 6900, y: 8525, w: 1100, d: 200, room: 'R-KITCHEN', label: 'serving hatch, 1100 — opens into the parents pod', height: 1400 },
  { id: 'FN-STOOL-1', kind: 'stool', x: 5755, y: 9470, w: 500, d: 500, room: 'R-KITCHEN', label: 'laundry basket', height: 400 },
  { id: 'FN-STOOL-2', kind: 'stool', x: 6305, y: 9470, w: 550, d: 550, room: 'R-KITCHEN', label: 'dustbin', height: 400 },
  { id: 'FN-BED-4', kind: 'bed', x: 14090, y: 10075, w: 1900, d: 900, room: 'R-HELP', label: 'bunk', height: 550 },
  { id: 'FN-SHELVES-3', kind: 'shelves', x: 14090, y: 9425, w: 600, d: 600, room: 'R-HELP', label: 'cupboard', height: 1400 },
  { id: 'FN-CONSOLE-15', kind: 'console', x: 10630, y: 9525, w: 450, d: 1400, room: 'R-KITCHEN', label: 'console', height: 800, face: 'W' },
  { id: 'FN-SOFA-5', kind: 'sofa', x: 13100, y: 9425, w: 750, d: 700, room: 'R-ENTRY', label: 'chair', height: 780, face: 'E' },
  { id: 'FN-SOFA-6', kind: 'sofa', x: 13100, y: 10325, w: 750, d: 700, room: 'R-ENTRY', label: 'chair', height: 780, face: 'E' },
  { id: 'FN-STOOL-3', kind: 'stool', x: 2475, y: 6715, w: 300, d: 300, room: 'R-P-DRESSING', label: 'bin', height: 400 },
  { id: 'FN-STOOL-4', kind: 'stool', x: 21705, y: 6715, w: 300, d: 300, room: 'R-GREAT', label: 'bin', height: 400 },
  { id: 'FN-SOFA-7', kind: 'sofa', x: 9673, y: 4637, w: 2805, d: 900, room: 'R-GREAT', label: '2-seat recliner sofa with the planter on its end', height: 780 },
  { id: 'FN-ARMCHAIR-3', kind: 'armchair', x: 12667.784, y: 3108.907, w: 824.432, d: 782.185, room: 'R-GREAT', label: 'Rocking chair', height: 780 },
  { id: 'FN-ARMCHAIR-4', kind: 'armchair', x: 13340.621, y: 4600.662, w: 918.758, d: 898.675, room: 'R-GREAT', label: 'Armchair', height: 780 },
  { id: 'FN-CONSOLE-16', kind: 'console', x: 7915, y: 2620, w: 9065, d: 1133.542, room: 'R-K-DEN', label: 'Corner unit', height: 750 },
  { id: 'FN-TREE-1', kind: 'tree', x: 850, y: 250, w: 700, d: 700, room: 'R-P-TERRACE', label: 'The terrace tree — real, in real grass', height: 2500 },
  { id: 'FN-TREE-2', kind: 'tree', x: 22930, y: 250, w: 700, d: 700, room: 'R-K-TERRACE', label: 'The terrace tree — real, in real grass', height: 2500 },
  { id: 'FN-TREE-3', kind: 'tree', x: 9673, y: 4637, w: 900, d: 900, room: 'R-GREAT', label: 'The tree growing off the sofa’s end', height: 2400 },
  { id: 'FN-BENCH-1', kind: 'bench', x: 750, y: 100, w: 900, d: 300, room: 'R-P-TERRACE', label: 'Jhoola', height: 1900 },
  { id: 'FN-BENCH-2', kind: 'bench', x: 22830, y: 100, w: 900, d: 300, room: 'R-K-TERRACE', label: 'Jhoola', height: 1900 },
]
